version: '3'

services:

    client:
        restart: unless-stopped
        build:
            context: .
        volumes:
            - .:/home/app
            - /home/app/node_modules
        working_dir: /home/app
        environment:
            NODE_ENV: "${NODE_ENV}"
            PORT: "${PORT}"
            API_URL: ${API_URL}
            HOST: "0.0.0.0"
            BASE_HREF: "/"
        ports:
            - "${PORT}:${PORT}"
        tty: True
        command: npm run start
