version: '3'

services:

    client:
        restart: unless-stopped
        build:
            context: .
        volumes:
            - .:/home/app
            - /home/app/node_modules
        working_dir: /home/app
        environment:
            NODE_ENV: ${NODE_ENV}
            PORT: ${PORT}
            HOST: "0.0.0.0"
        ports:
            - "${PORT}:${PORT}"
        tty: True
        command: npm run start
