version: '3'

services:

    client:
        restart: unless-stopped
        build:
            context: client
        volumes:
            - ./client:/home/app
            - /home/app/node_modules
        working_dir: /home/app
        environment:
            NODE_ENV: ${CLIENT_NODE_ENV}
            PORT: 5001
            API_URL: "/api/"
            BASE_HREF: "/client/"
        tty: True
        command: npm run start

    server:
        restart: unless-stopped
        build:
            context: server
        volumes:
            - ./server:/home/app
            - /home/app/node_modules
        working_dir: /home/app
        environment:
            NODE_ENV: ${SERVER_NODE_ENV}
            PORT: 5002
        tty: True
        command: npm run start

    nginx:
        image: nginx:alpine
        volumes:
            # nginx conf to be used
            - ./nginx/conf.d:/etc/nginx/conf.d/:ro
            # mount local volume as nginx document root
            # - ./html:/usr/share/nginx/html:ro
        ports:
            - ${NGINX_PORT}:80
        command: [nginx, '-g', 'daemon off;']
