version: '3'

services:

    server:
        restart: unless-stopped
        build:
            context: server
        volumes:
            - ./server:/home/app
            - /home/app/node_modules
        working_dir: /home/app
        environment:
            NODE_ENV: ${SERVER_NODE_ENV}
            PORT: ${SERVER_PORT}
            HOST: "0.0.0.0"
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        tty: True
        command: npm run start
