version: '3'

services:

    server:
        restart: unless-stopped
        build:
            context: .
        volumes:
            - .:/home/app
            - /home/app/node_modules
        working_dir: /home/app
        environment:
            NODE_ENV: ${NODE_ENV}
            PORT: ${PORT}
        ports:
            - ${PORT}:${PORT}
        tty: True
        command: npm run start
